[stockanalyser_targets]
stockanalyser-target ansible_host=stockanalyser-target ansible_port=22 ansible_user=appuser ansible_password=appuser ansible_python_interpreter=/usr/bin/python3 ansible_ssh_common_args='-o StrictHostKeyChecking=no'
